ci workflow updated

diff --git a/.github/workflows/ami_actions.yml b/.github/workflows/ami_actions.yml
--- a/.github/workflows/ami_actions.yml
+++ b/.github/workflows/ami_actions.yml
@@ -98,9 +98,33 @@ jobs:
 
     - name: Create Launch Template Version and Configure Auto Scaling Group
       run: |
-        aws ec2 create-launch-template-version --launch-template-name veeru-launch-template-3045c12 --source-version 1 --region ${{ secrets.AWS_REGION }} --image-id $AMI_ID
-        aws autoscaling update-auto-scaling-group --auto-scaling-group-name veeru-asg-547a25d --launch-template LaunchTemplateName=veeru-launch-template-3045c12,Version='$Latest' --region ${{ secrets.AWS_REGION }}
+        aws ec2 create-launch-template-version --launch-template-name veeru-launch-template-d0a9716 --source-version 1 --region ${{ secrets.AWS_REGION }} --image-id $AMI_ID
+        aws autoscaling update-auto-scaling-group --auto-scaling-group-name veeru-asg-d7c4332 --launch-template LaunchTemplateName=veeru-launch-template-d0a9716,Version='$Latest' --region ${{ secrets.AWS_REGION }}
 
-    - name: Create Launch Template Version and Configure Auto Scaling Group
+    - name: Instance Refreshing
       run: |
-        aws autoscaling start-instance-refresh --auto-scaling-group-name veeru-asg-547a25d 
+        aws autoscaling start-instance-refresh --auto-scaling-group-name veeru-asg-d7c4332 
+    
+    - name: Wait for Instance Refresh Completion
+      id: check-status
+      run: |
+        retries=0
+        max_retries=10
+        while [ $retries -lt $max_retries ]; do
+            status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name your-auto-scaling-group-name --query 'InstanceRefreshes[0].Status' --output text)
+            if [ "$status" = "Successful" ]; then
+                echo "Instance refresh succeeded."
+                exit 0
+            elif [ "$status" = "Failed" ]; then
+                echo "Instance refresh failed."
+                exit 1
+            fi
+            sleep 60s
+            retries=$((retries+1))
+        done
+        echo "Instance refresh did not complete within the specified time."
+        exit 1
+
+    - name: Update Workflow Status
+      if: ${{ job.status }}
+      run: exit ${{ steps.check-status.outcome }}
